[project]
name = "madeleine"
version = "0.1.0"
description = "A simple Microsoft BOND compact binary reader"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
license = "MIT"

[dependency-groups]
dev = [
    "ruff>=0.15.0",
    "ty>=0.0.15",
]
